POST http://localhost:5000/users/register
Content-Type: application/json

{
    "email": "daniel7@mail.com",
    "name": "Daniel",
    "password": "password",
    "password2": "password"
}

###

POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email": "daniel4@mail.com",
    "name": "Daniel",
    "password": "password",
    "password2": "password"
}
